name: Test web-client
on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  web-client-deploy-dapp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
      # - uses: actions/setup-node@v4
      #   with:
      #     node-version: 20
      #     cache: "npm"

      # - name: Install dependencies
      #   shell: bash
      #   run: npm install

      # - name: Run svelte-check
      #   run: npm run check

      - name: Install dfx
        uses: dfinity/setup-dfx@main
        with:
          dfx-version: "0.16.1"

      - name: Setup env to deploy
        run: |
          touch actions_identity.pem
          echo "${{ secrets.ESTATE_DAO_CANISTER_CONTROLLER_PRIVATE_KEY }}" > actions_identity.pem
          dfx identity import --storage-mode plaintext actions actions_identity.pem
          rm actions_identity.pem
          dfx identity use actions

      - name: Status
        run: dfx canister status webclient --network=ic
